{
 "title": "Backup",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Mysql full",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"timnet238\",type=\"full\",service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Influxdb incremental",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"timnet238\",type=\"incremental\",service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql incremental",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"timnet238\",type=\"incremental\",service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Influxdb full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"timnet238\",type=\"full\",service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last MySQL backup created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"timnet238\",service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last influxdb backup created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"timnet238\",service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}