- name: Install python3-flask-sqlalchemy & python3-pymysql
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
    update_cache: yes
    
- name: Add the user 'agama'
  user:
    name: agama

- name: Create a directory for Agama
  file:
    path: /opt/agama
    state: directory
    
- name: Download Dockerfile and agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile
    
- name: Build Docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      
- name: Start the containers
  community.docker.docker_container:
    name: agama-{{ item }}
    image: agama
    published_ports: "{{ agama_port + item }}:8000"
    restart_policy: always
    env:
      AGAMA_DATABASE_URI=mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  loop: "{{ range(nginx_containers_per_vm) }}"
  no_log: true
