- name: Install python3-flask-sqlalchemy & python3-pymysql
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
    update_cache: yes
    
- name: Add the user 'agama'
  user:
    name: agama

- name: Create a directory for Agama
  file:
    path: /opt/agama
    state: directory
    
- name: Download Dockerfile and agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile
    
- name: Build Docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      
- name: agama docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama
    image: agama
    published_ports: "8001:8000"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  #no_log: true
