- name: Create backup user
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    
- name: Update known hosts
  template:
    owner: backup
    group: backup
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    
