- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server

- name: Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql

- name: Start service mysql, if not started
  ansible.builtin.service:
    name: mysql
    state: started

- name: Enable service mysql, and not touch the state
  ansible.builtin.service:
    name: mysql
    enabled: yes

- name: copy the mysql config file and restart mysql server
  ansible.builtin.template:
    src: ../templates/override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: 
    - Restart mysql
    
- name: MySQL database 
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - reset mysql source
    - reset mysql replica
    
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
  no_log: true
    
- name: Create /home/backup/mysql directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0755'
    
- name: Create a mysql user backup
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_backup_password }}"
    priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Create configuration file
  ansible.builtin.template:
    src: ../templates/my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0600'
  no_log: true
  
- name: Create cron tab for creating backups
  ansible.builtin.template:
    src: ../templates/mysql-backup
    dest: /etc/cron.d/mysql-backup
  notify:
    - Restart cron
    
- name: Create replication user
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:REPLICATION SLAVE"
  no_log: true
  
- name: Enable read-only mode on a replica
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - reset mysql source
    - reset mysql replica
    
- name: Install mysql exporter
  apt:
    name:
      - prometheus-mysqld-exporter
      
- name: Create the my.cnf file
  template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.ex.j2
    mode: '0644'
  notify: Restart mysql exporter
  no_log: true
  
- name: Create mysql exporter user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
    
- name: force handlers
  meta: flush_handlers
  
- name: Update ARGS
  template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysql exporter
  
- name: Start and enable mysql exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
