# # config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://timnet238-2:9090/prometheus
  version: 1
  editable: false
  
- name: Influxdb (latency)
  type: influxdb
  access: proxy
  url: http://timnet238-2:8086
  database: latency
  
- name: Influxdb (telegraf)
  type: influxdb
  access: proxy
  url: http://timnet238-2:8086
  database: telegraf
