- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
    
- name: Restart influxdb_stats
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted

- name: Daemon reload
  ansible.builtin.shell: systemctl daemon-reload
