- name: Install keepalived
  apt:
    name: keepalived
    state: latest
    
- name: Create script directory
  file:
    path: /home/keepalived_script
    state: directory
    mode: '0755'
   
- name: Upload keepalived script
  template:
    src: keepalived_script.j2
    dest: /home/keepalived_script/keepalived_script
    mode: '0755'
  notify: restart keepalived
  
- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  no_log: yes
  
- name: Create keepalived_script user
  user:
    name: keepalived_script
    shell: /bin/bash
    
- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
    
- name: Check if Keepalived Exporter exists
  stat:
    path: /tmp/keepalived-exporter_1.4.0_linux_amd64.deb
  register: keepalived_file

- name: Download Keepalived Exporter
  get_url:
    url: http://backup/keepalived-exporter_1.4.0_linux_amd64.deb
    dest: /opt/keepalived-exporter_1.4.0_linux_amd64.deb


- name: Install Keepalived Exporter
  apt:
    deb: /opt/keepalived-exporter_1.4.0_linux_amd64.deb

- name: Move Keepalived Exporter to final location
  copy:
    src: /usr/bin/keepalived-exporter
    dest: /usr/local/bin/prometheus-keepalived-exporter
    mode: '0755'
    remote_src: yes

- name: Create keepalived exporter service
  ansible.builtin.template:
    src: prometheus-keepalived-exporter.service.j2
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  notify:
    - daemon reload
    - restart keepalived-exporter

- name: Start keepalived exporter
  ansible.builtin.service:
    name: prometheus-keepalived-exporter
    state: started
    enabled: yes
