- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Start and enable prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes

#- name: Install nginx
#  ansible.builtin.apt:
#    name: nginx
#    state: present


#- name: Replace a file
#  ansible.builtin.template:
#    src: ../nginx/templates/default
#    dest: /etc/nginx/sites-enabled/default
#  notify: Restart nginx

#- name: Start service nginx
#  ansible.builtin.service:
#    name: nginx
#    state: started
#    enabled: yes

- name: Apply configuration changes
  ansible.builtin.template:
    src: ../templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
  notify:
      - Restart prometheus
      
- name: Add configuration file to /etc/default/prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
  notify: 
      - Restart prometheus
