- name: Install bind9
  apt:
    name:
      - bind9
      - python3-dnspython
      
- name: Start bind9
  service:
    name: bind9
    state: started
    enabled: yes
    
- name: Copy the config file
  template:
    src: ../templates/named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  notify: restart bind9
  #no_log: true
  
- name: Copy the zone config
  template:
    src: ../templates/zone.j2
    dest: /var/cache/bind/db.clickit.io
    force: no
  notify: restart rndc
  when: inventory_hostname in groups['dns_primary']
  
- name: Copy the reversed zone config
  when: inventory_hostname in groups['dns_primary']
  template:
    src: zone.reversed.j2
    dest: /var/cache/bind/db.clickit.io.reversed
  #no_log: yes
  notify: restart rndc
  
- name: Execute handlers
  meta: flush_handlers
  
- name: Add the A records
  when: inventory_hostname == groups['dns_primary'][0]
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    server: "localhost"
    zone: "{{ domain_name }}"
    record: "backup"
    type: "A"
    value: "{{ backupserverip }}"
  #no_log: true
  notify: restart bind9
  
- name: Add the CNAME records
  when: inventory_hostname == groups['dns_primary'][0]
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    server: "localhost"
    zone: "{{ domain_name }}"
    record: "{{ item.key }}.{{ domain_name }}."
    type: "CNAME"
    value: "{{ item.value }}.{{ domain_name }}."
  loop: "{{ cname_records | dict2items }}"
  notify: restart bind9
  #no_log: true
    
