    
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
   
- name: Create rsyslog conf file
  ansible.builtin.template:
    src: ../templates/15-telegraf.conf
    dest: /etc/rsyslog.d/10-telegraf.conf
  notify:
    - Restart rsyslog

- name: Install prometheus node exporters
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure Node exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
      - Daemon reload
      - Restart node_exporter

- name: Start and enable node exporters service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
    
- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230300*
    
- name: Create /home/backup/restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0755'

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present
